#!/bin/sh

case "$2" in
        up)
            sh /home/jw/polybar-scripts/network-networkmanager.sh --update
        ;;
        down)
            sh /home/jw/polybar-scripts/network-networkmanager.sh --update
        ;;
esac
